vich_uploader:
    db_driver: orm

    mappings:
        paiement_image:
            uri_prefix: /images/paiements
            upload_destination: '%kernel.project_dir%/public/images/paiements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    
                    
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true