vich_uploader:
    db_driver: orm

    mappings:
        paiement_image:
            uri_prefix: /paiements/images
            upload_destination: '%kernel.project_dir%/public/paiements/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer   
                                
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true